version: 2.1

orbs:
  aws-cli: circleci/aws-cli@volatile
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  cp_build:
    docker:
      - image: cimg/base:2024.09
    steps:
     - setup_remote_docker
     - checkout
     - aws-cli/setup:
         profile_name: default
     - kubernetes/install-kubectl
     - run: 
         name: Kube Config
         command: |
                  aws configure set profile.default.aws_access_key_id "$AWS_ACCESS_KEY_ID" 
                  aws configure set profile.default.aws_secret_access_key "$AWS_SECRET_ACCESS_KEY>" 
                  aws configure set profile.default.region us-east-1
                  aws configure list --profile default
                  aws eks --region us-east-1 update-kubeconfig --name releng-eks-circleci
     - run:
         name: Install Dagger CLI
         command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
     - run: dagger core container from --address "alpine" with-exec --args "echo,hi" 

workflows:
  cp_build:
    jobs:
      - cp_build