version: 2.1

orbs:
  aws-cli: circleci/aws-cli@volatile
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  cp_build:
    docker:
      - image: cimg/base:2021.11
    resource_class: nautical-clouds/container
    steps:
     - checkout
     - aws-cli/setup:
         profile_name: default
     - kubernetes/install-kubectl
     - run:
         name: Install Dagger CLI
         command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
     - run:
         name: k8s dagger pods
         command: |
                  _EXPERIMENTAL_DAGGER_RUNNER_HOST="kube-pod://dagger-dagger-helm-engine-2ljkp?namespace=dagger"
                  export _EXPERIMENTAL_DAGGER_RUNNER_HOST

                  dagger query \<<EOF
                  {
                      container {
                          from(address:"alpine") {
                              withExec(args: ["uname", "-a"]) { stdout }
                          }
                      }
                  }
                  EOF

     - run: dagger core container from --address "alpine" with-exec --args "echo,hi" 

workflows:
  cp_build:
    jobs:
      - cp_build:
          context: cloud-global