version: 2.1

orbs:
  aws-cli: circleci/aws-cli@volatile
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  cp_build:
    docker:
      - image: cimg/base:2024.09
    steps:
     - setup_remote_docker
     - checkout
     - aws-cli/setup:
         profile_name: default
     - run: aws eks --region us-east-1 update-kubeconfig --name releng-eks-circleci
     - kubernetes/install-kubectl
     - run:
         name: Install Dagger CLI
         command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
     - run: dagger core container from --address "alpine" with-exec --args "echo,hi" 

workflows:
  cp_build:
    jobs:
      - cp_build