version: 2.1

orbs:
  aws-cli: circleci/aws-cli@volatile
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  cp_build:
    docker:
      - image: cimg/base:2025.02
    resource_class: nautical-clouds/container
    steps:
     - checkout
     - aws-cli/setup:
         profile_name: default
     - kubernetes/install-kubectl
     - run:
         name: Install Dagger CLI
         command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
     - run:
         name: k8s dagger pods
         command: |
                  kubectl get pods --all-namespaces
                   
                  DAGGER_ENGINE_POD_NAME="$(kubectl get pod \
                  --selector=name=dagger-dagger-helm-engine --namespace=dagger \
                  --output=jsonpath='{.items[0].metadata.name}')"
                  export DAGGER_ENGINE_POD_NAME

                  _EXPERIMENTAL_DAGGER_RUNNER_HOST="kube-pod://$DAGGER_ENGINE_POD_NAME?namespace=dagger"
                  export _EXPERIMENTAL_DAGGER_RUNNER_HOST

                  dagger query \<<EOF
                  {
                      container {
                          from(address:"alpine") {
                              withExec(args: ["uname", "-a"]) { stdout }
                          }
                      }
                  }
                  EOF
                  dagger core container from --address "alpine" with-exec --args "echo,hi" 

workflows:
  cp_build:
    jobs:
      - cp_build:
          context: cloud-global